replicaCount: 1

image:
  repository: quay.io/cloud-architecture-workshop/globex-web-reviews
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: d2b5006

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3

service:
  type: ClusterIP
  portName: http
  port: 8080
  containerPort: 8080

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

nodeEnv: prod

globexStoreApp:
  url: http://globex-store-app:8080
  service: globex-store-app
  getProductsPath: /services/catalog/product
  getProductListPath: /services/catalog/product/list/:ids
  cartPath: /services/cart
  customerPath: /services/customer/id/:custId
  orderPath: /services/order
activityTrackingService:
  url: http://activity-tracking:8080
  service: activity-tracking
  path: /track
recommendationEngine:
  url: http://recommendation-engine:8080
  service: recommendation-engine
  path: /score/product
reviewService:
  url: http://review-service:8080
  reviewPath: /review/product
  submitReviewPath: /review/submit
  summaryPath: /review/summary

sso:
  enabled: true
  authServer: 
  realm: 
  client:
  logLevel: "2"

subDomain:

argocd:
  enabled: true
  syncwave: "1"
